version: "3.5"

services:
  api01: &api
    image: jair-anderson-souza/rinha:latest
    hostname: api01
    platform: linux/amd64
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "245MB"

  api02:
    <<: *api
    image: jair-anderson-souza/rinha:latest
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./conf/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./conf/postgres.conf:/etc/postgresql/postgresql.conf:z
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "50MB"
networks:
  default:
    driver: bridge
    name: rinha
